const express = require("express");
let router = express.Router();
const nodeController = require("../controllers/Node.controller");
router.post("/history",nodeController.getNodeByAccountId);
router.get("/",nodeController.get);
router.get("/all",nodeController.getAll);
router.post("/",nodeController.post);
router.put("/",nodeController.put);
router.delete("/",nodeController.delete);
module.exports = router;